/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Ccliente;
import java.awt.event.ItemEvent;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
import modelo.Cliente;

/**
 *
 * @author jega_
 */
public final class frmClientes extends javax.swing.JFrame {
    
    private frmMenu menu;
    
    /**
     * Creates new form frmClientes
     */
    public frmClientes() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        URL iconURL = getClass().getResource("/imagenes/iconLo.png");
        if (iconURL != null) {
            ImageIcon icon = new ImageIcon(iconURL);
            setIconImage(icon.getImage());
        } else {
            System.err.println("No se pudo encontrar el archivo de ícono.");
        }
        
        try {
            ArrayList<String> listaMunicipios = cargarMunicipios();
            combMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(listaMunicipios.toArray(String[]::new)));
         } catch (IOException ex) {
            Logger.getLogger(frmClientes.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    public void setMenu(frmMenu menu) {
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSexo = new javax.swing.ButtonGroup();
        btngEstratos = new javax.swing.ButtonGroup();
        Backgroud = new javax.swing.JPanel();
        btnRetroceder = new javax.swing.JPanel();
        etiSexo = new javax.swing.JLabel();
        rabMasculino = new javax.swing.JRadioButton();
        rabFemenino = new javax.swing.JRadioButton();
        etiEstrato = new javax.swing.JLabel();
        rabEst1 = new javax.swing.JRadioButton();
        rabEst2 = new javax.swing.JRadioButton();
        rabEst3 = new javax.swing.JRadioButton();
        rabEst4 = new javax.swing.JRadioButton();
        rabEst5 = new javax.swing.JRadioButton();
        rabEst6 = new javax.swing.JRadioButton();
        etiPoliza = new javax.swing.JLabel();
        etiCedula = new javax.swing.JLabel();
        spPoliza = new javax.swing.JSeparator();
        txtPoliza = new javax.swing.JTextField();
        spCedula = new javax.swing.JSeparator();
        txtCedula = new javax.swing.JTextField();
        etiNombres = new javax.swing.JLabel();
        spNombres = new javax.swing.JSeparator();
        txtNombres = new javax.swing.JTextField();
        etiApellidos = new javax.swing.JLabel();
        spApellidos = new javax.swing.JSeparator();
        txtApellidos = new javax.swing.JTextField();
        etiMunicipio = new javax.swing.JLabel();
        etiBarrio = new javax.swing.JLabel();
        combMunicipio = new javax.swing.JComboBox<>();
        combBarrio = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        spMunicipio = new javax.swing.JSeparator();
        spBarrio = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        imgPerson = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        etiTitulo = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Cliente");
        setResizable(false);

        Backgroud.setBackground(new java.awt.Color(255, 255, 255));
        Backgroud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetroceder.setBackground(new java.awt.Color(234, 234, 234));
        btnRetroceder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiSexo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiSexo.setForeground(new java.awt.Color(0, 102, 255));
        etiSexo.setText("SEXO");
        btnRetroceder.add(etiSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 25, -1, -1));

        rabMasculino.setBackground(new java.awt.Color(235, 235, 235));
        btngSexo.add(rabMasculino);
        rabMasculino.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rabMasculino.setForeground(new java.awt.Color(51, 51, 51));
        rabMasculino.setText("Masculino");
        rabMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabMasculinoActionPerformed(evt);
            }
        });
        btnRetroceder.add(rabMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 49, -1, -1));

        rabFemenino.setBackground(new java.awt.Color(235, 235, 235));
        btngSexo.add(rabFemenino);
        rabFemenino.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rabFemenino.setForeground(new java.awt.Color(51, 51, 51));
        rabFemenino.setText("Femenino");
        btnRetroceder.add(rabFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 75, -1, -1));

        etiEstrato.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiEstrato.setForeground(new java.awt.Color(0, 102, 255));
        etiEstrato.setText("ESTRATO");
        btnRetroceder.add(etiEstrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 107, -1, -1));

        rabEst1.setBackground(new java.awt.Color(235, 235, 235));
        btngEstratos.add(rabEst1);
        rabEst1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rabEst1.setForeground(new java.awt.Color(51, 51, 51));
        rabEst1.setText("1");
        btnRetroceder.add(rabEst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 131, -1, -1));

        rabEst2.setBackground(new java.awt.Color(235, 235, 235));
        btngEstratos.add(rabEst2);
        rabEst2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rabEst2.setForeground(new java.awt.Color(51, 51, 51));
        rabEst2.setText("2");
        btnRetroceder.add(rabEst2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 157, -1, -1));

        rabEst3.setBackground(new java.awt.Color(235, 235, 235));
        btngEstratos.add(rabEst3);
        rabEst3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rabEst3.setForeground(new java.awt.Color(51, 51, 51));
        rabEst3.setText("3");
        btnRetroceder.add(rabEst3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 183, -1, -1));

        rabEst4.setBackground(new java.awt.Color(235, 235, 235));
        btngEstratos.add(rabEst4);
        rabEst4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rabEst4.setForeground(new java.awt.Color(51, 51, 51));
        rabEst4.setText("4");
        btnRetroceder.add(rabEst4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 209, -1, -1));

        rabEst5.setBackground(new java.awt.Color(235, 235, 235));
        btngEstratos.add(rabEst5);
        rabEst5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rabEst5.setForeground(new java.awt.Color(51, 51, 51));
        rabEst5.setText("5");
        btnRetroceder.add(rabEst5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 235, -1, -1));

        rabEst6.setBackground(new java.awt.Color(235, 235, 235));
        btngEstratos.add(rabEst6);
        rabEst6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rabEst6.setForeground(new java.awt.Color(51, 51, 51));
        rabEst6.setText("6");
        btnRetroceder.add(rabEst6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 261, -1, -1));

        etiPoliza.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiPoliza.setForeground(new java.awt.Color(0, 102, 255));
        etiPoliza.setText("PÓLIZA");
        btnRetroceder.add(etiPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 25, -1, 30));

        etiCedula.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiCedula.setForeground(new java.awt.Color(0, 102, 255));
        etiCedula.setText("CÉDULA");
        btnRetroceder.add(etiCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, 20));

        spPoliza.setBackground(new java.awt.Color(255, 255, 255));
        spPoliza.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 165, 10));

        txtPoliza.setBackground(new java.awt.Color(224, 224, 224));
        txtPoliza.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtPoliza.setForeground(new java.awt.Color(51, 51, 51));
        txtPoliza.setBorder(null);
        btnRetroceder.add(txtPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 165, 25));

        spCedula.setBackground(new java.awt.Color(255, 255, 255));
        spCedula.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 165, 10));

        txtCedula.setBackground(new java.awt.Color(224, 224, 224));
        txtCedula.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(51, 51, 51));
        txtCedula.setBorder(null);
        btnRetroceder.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 165, 25));

        etiNombres.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiNombres.setForeground(new java.awt.Color(0, 102, 255));
        etiNombres.setText("NOMBRES");
        btnRetroceder.add(etiNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        spNombres.setBackground(new java.awt.Color(255, 255, 255));
        spNombres.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 165, 10));

        txtNombres.setBackground(new java.awt.Color(224, 224, 224));
        txtNombres.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(51, 51, 51));
        txtNombres.setBorder(null);
        btnRetroceder.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 165, 25));

        etiApellidos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiApellidos.setForeground(new java.awt.Color(0, 102, 255));
        etiApellidos.setText("APELLIDOS");
        btnRetroceder.add(etiApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        spApellidos.setBackground(new java.awt.Color(255, 255, 255));
        spApellidos.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 165, 10));

        txtApellidos.setBackground(new java.awt.Color(224, 224, 224));
        txtApellidos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(51, 51, 51));
        txtApellidos.setBorder(null);
        btnRetroceder.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 165, 25));

        etiMunicipio.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiMunicipio.setForeground(new java.awt.Color(0, 102, 255));
        etiMunicipio.setText("MUNICIPIO");
        btnRetroceder.add(etiMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        etiBarrio.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiBarrio.setForeground(new java.awt.Color(0, 102, 255));
        etiBarrio.setText("BARRIO");
        btnRetroceder.add(etiBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        combMunicipio.setBackground(new java.awt.Color(224, 224, 224));
        combMunicipio.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        combMunicipio.setForeground(new java.awt.Color(51, 51, 51));
        combMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BARANOA", "BARRANQUILLA", "CAMPO DE LA CRUZ", "CANDELARIA", "GALAPA", "JUAN DE ACOSTA", "LURUACO", "MALAMBO", "MANATÍ", "PALMAR DE VARELA", "PIOJÓ", "PONEDERA", "PUERTO COLOMBIA", "REPELÓN", "SABANAGRANDE", "SABANALARGA", "SANTA LUCÍA", "SANTO TOMÁS", "SOLEDAD", "SUÁN", "TUBARÁ", "USIACURÍ" }));
        combMunicipio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        combMunicipio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combMunicipioItemStateChanged(evt);
            }
        });
        btnRetroceder.add(combMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, 30));

        combBarrio.setBackground(new java.awt.Color(224, 224, 224));
        combBarrio.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        combBarrio.setForeground(new java.awt.Color(51, 51, 51));
        combBarrio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        combBarrio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combBarrioItemStateChanged(evt);
            }
        });
        combBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combBarrioActionPerformed(evt);
            }
        });
        btnRetroceder.add(combBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 30));

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        btnRetroceder.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 90, 30));

        spMunicipio.setBackground(new java.awt.Color(255, 255, 255));
        spMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 140, 10));

        spBarrio.setBackground(new java.awt.Color(255, 255, 255));
        spBarrio.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 270, 10));

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("RETROCEDER");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnRetroceder.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 90, 30));

        Backgroud.add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 730, 300));

        imgPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/male-clerk-at-a-convenience-store-upper-body-svgrepo-com.png"))); // NOI18N
        Backgroud.add(imgPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlTitulo.setBackground(new java.awt.Color(0, 153, 255));

        etiTitulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        etiTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etiTitulo.setText("FORMULARIO DE REGISTRO");

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aaa-barranquilla-logo-90D5360AB1-seeklogo.com.png"))); // NOI18N

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                        .addComponent(imgLogo)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                        .addComponent(etiTitulo)
                        .addGap(42, 42, 42))))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Backgroud.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 730, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rabMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rabMasculinoActionPerformed

    public static int verificador(String num) {
         try {
            Integer.valueOf(num);
            //return Integer.parseInt(num);
            return 1;
         } catch (NumberFormatException ex) {
             return -1;
         }
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        String sex = null;
        int est = -1;
        int nroref = -1;
        long ced = -1;
        String nom = null;
        String ape = null;
        String bar;
        String mun;
        boolean ver = true;
        String msg ="";
        
        if (verificador(txtPoliza.getText()) != -1  && verificador(txtPoliza.getText()) >= 0) {
            List<Integer> numerosPoliza = menu.obtenerNumerosPoliza();
            nroref = Integer.parseInt(txtPoliza.getText());
            if (numerosPoliza.contains(nroref)) {
                msg += "El numero de PÓLIZA ya existe\n";
                ver = false;
            }
        } else {
            msg += "Numero de PÓLIZA invalido\n";
            ver = false;
        }
        
        if (verificador(txtCedula.getText()) != -1  && verificador(txtCedula.getText()) >= 0) {
            ced = Long.parseLong(txtCedula.getText());
        } else {
            msg += "Numero de CEDULA invalida\n";
            ver = false;
        }
        
        if (txtNombres.getText().isEmpty()) {
            ver = false;
            msg+="Campo NOMBRES sin completar\n";
        } else {
            nom=txtNombres.getText().toUpperCase();
        }
        
        if (txtApellidos.getText().isEmpty()) {
            ver = false;
            msg+="Campo APELLIDOS sin completar\n";
        } else {
            ape=txtApellidos.getText().toUpperCase();
        }

        if (combBarrio.getSelectedItem() == null) {
            ver = false;
            msg += "Debe seleccionar un BARRIO.\n";
        }
 
        bar=String.valueOf(combBarrio.getSelectedItem());
        mun=String.valueOf(combMunicipio.getSelectedItem());
        
        if (rabEst1.isSelected()) {
            est = Integer.parseInt(rabEst1.getText());
        } else if (rabEst2.isSelected()) {
            est = Integer.parseInt(rabEst2.getText());
        } else if (rabEst3.isSelected()) {
           est = Integer.parseInt(rabEst3.getText());
        } else if (rabEst4.isSelected()) {
            est = Integer.parseInt(rabEst4.getText());
        } else if (rabEst5.isSelected()) {
            est = Integer.parseInt(rabEst5.getText());
        } else if (rabEst6.isSelected()) {
            est = Integer.parseInt(rabEst6.getText());
        } else {
            msg += "Campo ESTRATO sin completar\n";
            ver = false;
        }
        
        if (rabMasculino.isSelected()) {
            sex = rabMasculino.getText();
        } else if (rabFemenino.isSelected()) {
            sex = rabFemenino.getText();
        } else {
            msg += "Campo SEXO sin completar\n";
            ver = false;
        }
        
        if (ver) {
            Cliente M = new Cliente(nroref,ced,nom,ape,bar,mun,sex,est);
        
            Ccliente m = new Ccliente();
        
        
            JOptionPane.showMessageDialog(null, "Registro Guardado", "Mensaje", HEIGHT);
            try {
                m.Registrar(M);
                txtPoliza.setText("");
                txtCedula.setText("");
                txtNombres.setText("");
                txtApellidos.setText("");
                btngSexo.clearSelection();
                btngEstratos.clearSelection();
                menu.ActualizarTabClientes();
            } catch (IOException ex) {
                //Logger.getLogger(frmCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, msg + "Por favor, complete todos los campos.");
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    public ArrayList<String> cargarMunicipios() throws IOException {
        String archivo = "baseDatos/lugares/municipios/Municipios.txt";
        ArrayList<String> municipios = new ArrayList<>();
        try (FileReader reader = new FileReader(archivo)) {
            BufferedReader br = new BufferedReader(reader);
            String linea;
            while ((linea = br.readLine()) != null) {
            municipios.add(linea.trim());
            }
        }
        return municipios;
    }


    
    public ArrayList<String> barrios(String mun) throws IOException {
        String archivo = "baseDatos/lugares/barrios/" + mun + ".txt";
        ArrayList<String> barrios = new ArrayList<>();
        try (FileReader reader = new FileReader(archivo)) {
            BufferedReader br = new BufferedReader(reader);
            String linea;
            
            while ((linea = br.readLine()) != null) {
            barrios.add(linea.trim());
            }
        }
        return barrios;
    }


    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void combBarrioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combBarrioItemStateChanged

    }//GEN-LAST:event_combBarrioItemStateChanged

    private void combBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combBarrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combBarrioActionPerformed

    private void combMunicipioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combMunicipioItemStateChanged
       if (evt.getStateChange() == ItemEvent.SELECTED) {
            String municipioSeleccionado = (String) combMunicipio.getSelectedItem();
            try {
                ArrayList<String> listaBarrios = barrios(municipioSeleccionado);
                combBarrio.setModel(new javax.swing.DefaultComboBoxModel<>(listaBarrios.toArray(String[]::new)));
            } catch (IOException ex) {
                Logger.getLogger(frmClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_combMunicipioItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(frmClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                new frmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroud;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel btnRetroceder;
    private javax.swing.ButtonGroup btngEstratos;
    private javax.swing.ButtonGroup btngSexo;
    private javax.swing.JComboBox<String> combBarrio;
    private javax.swing.JComboBox<String> combMunicipio;
    private javax.swing.JLabel etiApellidos;
    private javax.swing.JLabel etiBarrio;
    private javax.swing.JLabel etiCedula;
    private javax.swing.JLabel etiEstrato;
    private javax.swing.JLabel etiMunicipio;
    private javax.swing.JLabel etiNombres;
    private javax.swing.JLabel etiPoliza;
    private javax.swing.JLabel etiSexo;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgPerson;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JRadioButton rabEst1;
    private javax.swing.JRadioButton rabEst2;
    private javax.swing.JRadioButton rabEst3;
    private javax.swing.JRadioButton rabEst4;
    private javax.swing.JRadioButton rabEst5;
    private javax.swing.JRadioButton rabEst6;
    private javax.swing.JRadioButton rabFemenino;
    private javax.swing.JRadioButton rabMasculino;
    private javax.swing.JSeparator spApellidos;
    private javax.swing.JSeparator spBarrio;
    private javax.swing.JSeparator spCedula;
    private javax.swing.JSeparator spMunicipio;
    private javax.swing.JSeparator spNombres;
    private javax.swing.JSeparator spPoliza;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPoliza;
    // End of variables declaration//GEN-END:variables
}
