/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author jega_
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Cargar el ícono como un recurso
        URL iconURL = getClass().getResource("/imagenes/iconLo.png");
        if (iconURL != null) {
            ImageIcon icon = new ImageIcon(iconURL);
            setIconImage(icon.getImage());
        } else {
            System.err.println("No se pudo encontrar el archivo de ícono.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        imgBanner = new javax.swing.JLabel();
        imgUser = new javax.swing.JLabel();
        etiIniciarSesion = new javax.swing.JLabel();
        etiUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        spUsuario = new javax.swing.JSeparator();
        etiContrasena = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        spContrasena = new javax.swing.JSeparator();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Recurso 1.png"))); // NOI18N
        Background.add(imgBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 0, -1, -1));

        imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Recurso 3.png"))); // NOI18N
        Background.add(imgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        etiIniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        etiIniciarSesion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        etiIniciarSesion.setForeground(new java.awt.Color(0, 102, 204));
        etiIniciarSesion.setText("INICIAR SESIÓN");
        Background.add(etiIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        etiUsuario.setBackground(new java.awt.Color(0, 0, 0));
        etiUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiUsuario.setForeground(new java.awt.Color(0, 102, 204));
        etiUsuario.setText("Usuario");
        Background.add(etiUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setToolTipText("Digita tu usuario aquí.");
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        Background.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 210, 30));

        spUsuario.setBackground(new java.awt.Color(0, 102, 204));
        spUsuario.setForeground(new java.awt.Color(0, 102, 204));
        Background.add(spUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 210, 10));

        etiContrasena.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiContrasena.setForeground(new java.awt.Color(0, 102, 204));
        etiContrasena.setText("Contraseña");
        Background.add(etiContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setToolTipText("Digita la contraseña.");
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        Background.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 210, 30));

        spContrasena.setBackground(new java.awt.Color(0, 102, 204));
        spContrasena.setForeground(new java.awt.Color(0, 153, 255));
        Background.add(spContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 210, 10));

        btnIniciarSesion.setBackground(new java.awt.Color(0, 102, 204));
        btnIniciarSesion.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        Background.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        char clave[] = txtPassword.getPassword();
        String clavedef = new String(clave);
        if(txtUsuario.getText().equals("Administrador") && clavedef.equals("12345")) {
            this.dispose();
            JOptionPane.showMessageDialog(null, "Bienvenido\nHas ingresado satisfactoriamente al sistema", "Mensaje de bienvenida",JOptionPane.INFORMATION_MESSAGE );
            frmMenu ventana2 = new frmMenu();
            ventana2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\nPor favor ingrese un usuario y/o contraseña correctos", "Acceso denegado",JOptionPane.ERROR_MESSAGE);
        }
     
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
         if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtPassword.requestFocusInWindow();
         }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            char clave[]=txtPassword.getPassword();
            String clavedef=new String(clave);
                if (txtUsuario.getText().equals("Administrador") && clavedef.equals("12345")){
                 this.dispose();

                 JOptionPane.showMessageDialog(null, "Bienvenido\nHas ingresado satisfactoriamente al sistema", "Mensaje de bienvenida",JOptionPane.INFORMATION_MESSAGE );
                 frmMenu ventana2 = new frmMenu();
                 ventana2.setVisible(true);
                 }else {
                 JOptionPane.showMessageDialog(null, "Acceso denegado:\nPor favor ingrese un usuario y/o contraseña correctos", "Acceso denegado",JOptionPane.ERROR_MESSAGE);
                 }
         }
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel etiContrasena;
    private javax.swing.JLabel etiIniciarSesion;
    private javax.swing.JLabel etiUsuario;
    private javax.swing.JLabel imgBanner;
    private javax.swing.JLabel imgUser;
    private javax.swing.JSeparator spContrasena;
    private javax.swing.JSeparator spUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
