/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Cfacturas;
import controlador.Clecturas;
import java.io.IOException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
import modelo.Facturas;
import modelo.Lecturas;

/**
 *
 * @author jega_
 */
public class frmLecturas extends javax.swing.JFrame {

    private frmMenu menu;
    /**
     * Creates new form frmLecturas
     */
    public frmLecturas() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        URL iconURL = getClass().getResource("/imagenes/iconLo.png");
        if (iconURL != null) {
            ImageIcon icon = new ImageIcon(iconURL);
            setIconImage(icon.getImage());
        } else {
            System.err.println("No se pudo encontrar el archivo de ícono.");
        }
    }
    
    public void setMenu(frmMenu menu) {
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroud = new javax.swing.JPanel();
        btnRetroceder = new javax.swing.JPanel();
        etiPoliza = new javax.swing.JLabel();
        etiLecturaAnterior = new javax.swing.JLabel();
        spPoliza = new javax.swing.JSeparator();
        txtPoliza = new javax.swing.JTextField();
        spLecturaAnterior = new javax.swing.JSeparator();
        txtLecturaAnterior = new javax.swing.JTextField();
        etiLecturaActual = new javax.swing.JLabel();
        spLecturaActual = new javax.swing.JSeparator();
        txtLecturaActual = new javax.swing.JTextField();
        etiFecha = new javax.swing.JLabel();
        spFecha = new javax.swing.JSeparator();
        txtFecha = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        imgPerson = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        etiTitulo = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lectura");
        setResizable(false);

        Backgroud.setBackground(new java.awt.Color(255, 255, 255));
        Backgroud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetroceder.setBackground(new java.awt.Color(234, 234, 234));
        btnRetroceder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiPoliza.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiPoliza.setForeground(new java.awt.Color(0, 102, 255));
        etiPoliza.setText("NRO. PÓLIZA");
        btnRetroceder.add(etiPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        etiLecturaAnterior.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiLecturaAnterior.setForeground(new java.awt.Color(0, 102, 255));
        etiLecturaAnterior.setText("LECTURA ANTERIOR");
        btnRetroceder.add(etiLecturaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 20));

        spPoliza.setBackground(new java.awt.Color(255, 255, 255));
        spPoliza.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 165, 10));

        txtPoliza.setBackground(new java.awt.Color(224, 224, 224));
        txtPoliza.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtPoliza.setForeground(new java.awt.Color(51, 51, 51));
        txtPoliza.setBorder(null);
        btnRetroceder.add(txtPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 165, 30));

        spLecturaAnterior.setBackground(new java.awt.Color(255, 255, 255));
        spLecturaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spLecturaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 165, 10));

        txtLecturaAnterior.setBackground(new java.awt.Color(224, 224, 224));
        txtLecturaAnterior.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtLecturaAnterior.setForeground(new java.awt.Color(51, 51, 51));
        txtLecturaAnterior.setBorder(null);
        btnRetroceder.add(txtLecturaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 165, 30));

        etiLecturaActual.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiLecturaActual.setForeground(new java.awt.Color(0, 102, 255));
        etiLecturaActual.setText("LECTURA ACTUAL");
        btnRetroceder.add(etiLecturaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        spLecturaActual.setBackground(new java.awt.Color(255, 255, 255));
        spLecturaActual.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spLecturaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 165, 10));

        txtLecturaActual.setBackground(new java.awt.Color(224, 224, 224));
        txtLecturaActual.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtLecturaActual.setForeground(new java.awt.Color(51, 51, 51));
        txtLecturaActual.setBorder(null);
        btnRetroceder.add(txtLecturaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 165, 30));

        etiFecha.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiFecha.setForeground(new java.awt.Color(0, 102, 255));
        etiFecha.setText("FECHA");
        btnRetroceder.add(etiFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        spFecha.setBackground(new java.awt.Color(255, 255, 255));
        spFecha.setForeground(new java.awt.Color(255, 255, 255));
        btnRetroceder.add(spFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 165, 10));

        txtFecha.setBackground(new java.awt.Color(224, 224, 224));
        txtFecha.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(51, 51, 51));
        txtFecha.setBorder(null);
        btnRetroceder.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 165, 30));

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        btnRetroceder.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("RETROCEDER");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnRetroceder.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 110, 40));

        Backgroud.add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 730, 160));

        imgPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/male-clerk-at-a-convenience-store-upper-body-svgrepo-com.png"))); // NOI18N
        Backgroud.add(imgPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlTitulo.setBackground(new java.awt.Color(0, 153, 255));

        etiTitulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        etiTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etiTitulo.setText("REGISTRO DE LECTURA");

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aaa-barranquilla-logo-90D5360AB1-seeklogo.com.png"))); // NOI18N

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                        .addComponent(imgLogo)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                        .addComponent(etiTitulo)
                        .addGap(111, 111, 111))))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Backgroud.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 730, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int verificador(String num) {
         try {
            Integer.valueOf(num);
            return Integer.parseInt(num);
         } catch (NumberFormatException ex) {
             return -1;
         }
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int nroRef = -1;
        int lectAct = -1;
        int lectAnt = -1;
        String fecha = null;

        boolean ver = true;
        String msg ="";

        // Verificación de número de póliza
        if (verificador(txtPoliza.getText()) != -1 && verificador(txtPoliza.getText()) >= 0) {
            List<Integer> numerosPoliza = menu.obtenerNumerosPoliza();
            try {
                nroRef = Integer.parseInt(txtPoliza.getText());
                if (!numerosPoliza.contains(nroRef)) {
                    msg += "El numero de PÓLIZA no existe o no se encuentra registrado en la base de datos\n";
                    ver = false;
                }
            } catch (NumberFormatException e) {
                msg += "Número de PÓLIZA inválido\n";
                ver = false;
            }
        } else {
            msg += "Número de PÓLIZA inválido\n";
            ver = false;
        }

        // Verificación de lectura anterior
        try {
            lectAnt = Integer.parseInt(txtLecturaAnterior.getText());
        } catch (NumberFormatException e) {
            msg += "Número de LECTURA ANTERIOR inválido\n";
            ver = false;
        }

        // Verificación de lectura actual
        try {
            lectAct = Integer.parseInt(txtLecturaActual.getText());
        } catch (NumberFormatException e) {
            msg += "Número de LECTURA ACTUAL inválido\n";
            ver = false;
        }

        // Verificación de fecha
        if (txtFecha.getText().isEmpty()) {
            ver = false;
            msg += "Campo FECHA sin completar\n";
        } else {
            fecha = txtFecha.getText().toUpperCase();
        }

        if (ver) {
            Lecturas M = new Lecturas(nroRef, lectAnt, lectAct, fecha);
            Clecturas m = new Clecturas();

            String[] datos = menu.datosFilaCliente(nroRef);
            int valorAcu = lectAct * Integer.parseInt(menu.dtm3Acu.getValueAt((Integer.parseInt(datos[7]) - 1), 1).toString());
            int valorAlc = (valorAcu * Integer.parseInt(menu.dtm3Alc.getValueAt((Integer.parseInt(datos[7]) - 1), 1).toString())) / 100;
            int valorAse = 19 * Integer.parseInt(menu.dtm3Ase.getValueAt((Integer.parseInt(datos[7]) - 1), 1).toString());
            int totalServ = valorAcu + valorAlc + valorAse;
            int valorSub = (totalServ * Integer.parseInt(menu.dtm3Sub.getValueAt((Integer.parseInt(datos[7]) - 1), 1).toString())) / 100;
            int totalFact = totalServ - valorSub;
            Facturas F = new Facturas(nroRef, fecha, totalFact);
            Cfacturas f = new Cfacturas();

            JOptionPane.showMessageDialog(null, "Registro Guardado", "Mensaje", HEIGHT);
            try {
                m.Registrar(M);
                f.Registrar(F);
                txtPoliza.setText("");
                txtLecturaAnterior.setText("");
                txtLecturaActual.setText("");
                txtFecha.setText("");
                menu.ActualizarTabLecturas();
            } catch (IOException ex) {
            }
        } else {
            JOptionPane.showMessageDialog(null, msg + "Por favor, complete todos los campos.");
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLecturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLecturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLecturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLecturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(frmLecturas.class.getName()).log(Level.SEVERE, null, ex);
                }
                new frmLecturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroud;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel btnRetroceder;
    private javax.swing.JLabel etiFecha;
    private javax.swing.JLabel etiLecturaActual;
    private javax.swing.JLabel etiLecturaAnterior;
    private javax.swing.JLabel etiPoliza;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgPerson;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JSeparator spFecha;
    private javax.swing.JSeparator spLecturaActual;
    private javax.swing.JSeparator spLecturaAnterior;
    private javax.swing.JSeparator spPoliza;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtLecturaActual;
    private javax.swing.JTextField txtLecturaAnterior;
    private javax.swing.JTextField txtPoliza;
    // End of variables declaration//GEN-END:variables
}
